# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
    - name: Setup swift
      uses: actions/checkout@v3
    - name: Clean build
      run: rm -rf .build
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app && /usr/bin/xcodebuild -version
    - name: Run all tests
      run: xcodebuild test -scheme WatchList -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' | xcpretty
