# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: "Swift & CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
    - name: Setup swift
      uses: actions/checkout@v3
    - name: Clean build
      run: rm -rf .build
    - name: Build and run tests
      run: sh ./Scripts/check-code-coverage.sh
      
  analyze:
    name: Analyze
    runs-on: ${{ (matrix.language == 'swift' && 'self-hosted') }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'swift' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - run: |
        echo "Run, Build Application using script"
        set -o pipefail && env NSUnbufferedIO=YES xcodebuild build -scheme WatchList -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1" -allowProvisioningUpdates

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
